
name: Integration tests workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'static/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'static/**'

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
    - run: 'pwd'
    - run: 'echo "Integration test done!!"'
