
name: Unit tests workflow

on:
  workflow_dispatch:
  push:
    paths:
      - 'static/**'
  pull_request:
    paths:
      - 'static/**'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - run: 'echo "No code change! Skip test!!"'
