
name: Unit tests workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'static/**'
  pull_request:
    branches:
      - main
    paths:
      - 'static/**'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - run: 'echo "No code change! Skip unit test!!"'

  integration-test:
    runs-on: ubuntu-latest
    steps:
    - run: 'echo "No code change! Skip integration test!!"'
